language: c

os: osx
env:
  - PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig

addons:
  apt:
    packages:
      - libogg-dev
      - libopus-dev

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew bundle; fi

script:
  - ./autogen.sh
  - ./configure
  - make
  - make distcheck
