language: c

os: osx

addons:
  apt:
    packages:
      - libogg-dev
      - libopus-dev

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install libogg opus openssl; fi

script:
  - ./autogen.sh
  - ./configure
  - make
  - make distcheck
